# Generated by Django 4.2.1 on 2023-05-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Autenticacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectName", models.CharField(max_length=100)),
                (
                    "archivoDatos",
                    models.FileField(upload_to="documents/datasetsProyectos/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("project_state", models.IntegerField(default=0)),
                ("variable_a_predecir", models.CharField(blank=True, max_length=100)),
                (
                    "tipo_prediccion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clasificacion", "clasificacion"),
                            ("regresion", "regresion"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tiposDatosProcesados",
                    models.FileField(
                        blank=True, upload_to="documents/tiposDatosProcesados/"
                    ),
                ),
                (
                    "archivoDatosNA",
                    models.FileField(
                        blank=True, upload_to="documents/datasetsProyectosProcesados/"
                    ),
                ),
                ("version_datos_a_usar", models.DateTimeField(auto_now_add=True)),
                (
                    "tipos_de_modelos",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "train_test_split",
                    models.FloatField(blank=True, max_length=100, null=True),
                ),
                (
                    "test_val_split",
                    models.FloatField(blank=True, max_length=100, null=True),
                ),
                ("preprocesado", models.BooleanField(default=0)),
                (
                    "treat_na_dict",
                    models.FileField(blank=True, upload_to="documents/treat_na/"),
                ),
                (
                    "columnas_originales",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="Autenticacion.usuario",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "projectName")},
            },
        ),
    ]
